### PR TITLE
Update Header to better match specs

### PR DESCRIPTION
**Pull request by Wondertan**
Extracted from #305

### CODE REVIEW

**Comment by Wondertan** [comment]
Related: https://github.com/lazyledger/lazyledger-core/pull/305#issuecomment-829232897

**Review by liamsi — APPROVED** [review]
LGTM

**Comment by Wondertan** [comment]
@liamsi, let's merge #316 first, as it fixes the failing test, which @evan-forbes was also observing and reported me

**Comment by Wondertan** [comment]
Tests passed, merging

**Pull request merged**
